api_platform:
    show_webby: false
    # The title of the API.
    title: API BileMo
    # The description of the API.
    description: 'Api to manage phones and customers'
    version: 0.1
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
             apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            enabled: false
            items_per_page: 10
    http_cache:
        etag: true
        max_age: 3600
        shared_max_age: 3600